default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  host: localhost
  encoding: utf8
  collation: utf8_general_ci

development:
  <<: *default
  database: social_development

production:
  <<: *default
  database: social_production
